Feature gpu usage
Eraden/amdgpud pull request #60
Opened 2023-04-18 05:30 UTC by Eraden

2023-04-18 21:45 UTC, emansom commented
Thanks for implementing this. When testing a locally built amdfand from this PR: the UsagePoint matrix currently doesn't seem to blast the fans during gaming with the following `mapping.toml`. I suspect the matrixes need to merged internally, then whichever has the highest speed should take precedent.

```
temp_input = "temp1_input"
log_level = "Debug"
update_rate = 6000

[[temp_matrix]]
temp = 0.0
speed = 0.0

[[temp_matrix]]
temp = 30.0
speed = 0.0

[[temp_matrix]]
temp = 35.0
speed = 10.0

[[temp_matrix]]
temp = 40.0
speed = 25.0

[[temp_matrix]]
temp = 50.0
speed = 35.0

[[temp_matrix]]
temp = 60.0
speed = 70.0

[[usage_matrix]]
usage = 20.0
speed = 10.0

[[usage_matrix]]
usage = 30.0
speed = 65.0

[[usage_matrix]]
usage = 65.0
speed = 70.0
```

2023-04-19 04:29 UTC, Eraden commented
Yes. This is still in progress but it should works now. When did you cloned and built? Only newest version is working correctly

2023-04-19 10:34 UTC, emansom commented
> Yes. This is still in progress but it should works now. When did you cloned and built? Only newest version is working correctly

I built it yesterday 23:21:39 CEST (Central European Summer Time). Testing with a rebuilt version now yields the same result. If the matrix calculations are working correctly, then I hypothesize the usage calculation needs to be calculated differently.

As some game engines tend to batch queue draw calls, where a few milliseconds the GPU is at 99% load, and most of the time 0-10%.

A way to combat this would be to calculate an accurate busy percentage by comparing measurements, similar to [how nvtop implements it](https://github.com/Syllo/nvtop/blob/master/src/extract_gpuinfo_amdgpu.c#L902).

2023-04-19 19:15 UTC, Eraden commented
Thanks for resources. And I will also try to solve this ASAP

2023-04-20 19:35 UTC, Eraden commented
Hi, current code should works properly. I tested it with `glmark2` and amdfand did use GPU usage to manage fan speed.

I need to fix GUI so this will be on hold until fix but you can compile from this branch and use it safely.

```
cargo build --release --bin amdfand
```

2023-04-21 13:16 UTC, emansom commented
It works better, it does detect GPU usage now and ramps up accordingly! However, it now seems to sporadically set the speed to 100.

This was observed while playing an DXVK game (Need for Speed: Most Wanted 2012 edition) on a RX 580.

Relevant debug log:
```
apr 21 15:10:46 x11sslf systemd[1]: Started AMD GPU fan daemon.
apr 21 15:10:46 x11sslf amdfand[1273420]: Config { path: "/etc/amdfand/mapping.toml", temp_input: Some(TempInput(1)), log_level: Debug, cards: None, update_rate: 6000, temp_matrix: [TempPoint { temp: 0.0, speed: 0.0 }, TempPoint { temp: 30.0, speed: 0.0 }, TempPoint { temp: 35.0, speed: 10.0 }, TempPoint { temp: 40.0, speed: 25.0 }, TempPoint { temp: 50.0, speed: 35.0 }, TempPoint { temp: 60.0, speed: 70.0 }], usage_matrix: [UsagePoint { usage: 0.0, speed: 0.0 }, UsagePoint { usage: 30.0, speed: 10.0 }, UsagePoint { usage: 100.0, speed: 33.0 }] }
apr 21 15:10:46 x11sslf amdfand[1273420]: 2023-04-21T13:10:46.114077Z DEBUG amdgpu::lock_file: Creating pid lock for path "/var/lib/amdfand/amdfand.pid"
apr 21 15:10:46 x11sslf amdfand[1273420]: 2023-04-21T13:10:46.114104Z DEBUG amdgpu::lock_file: PID LOCK acquiring /var/lib/amdfand/amdfand.pid
apr 21 15:10:46 x11sslf amdfand[1273420]: 2023-04-21T13:10:46.114111Z DEBUG amdgpu::lock_file: No collision detected
apr 21 15:10:46 x11sslf amdfand[1273420]: 2023-04-21T13:10:46.114199Z  INFO amdgpu::utils: opening hw mon for Card(0)
apr 21 15:10:46 x11sslf amdfand[1273420]: 2023-04-21T13:10:46.114231Z  INFO amdgpu::utils: is vendor ok? true
apr 21 15:10:46 x11sslf amdfand[1273420]: 2023-04-21T13:10:46.114250Z  INFO amdgpu::utils: is hwmon name ok? true
apr 21 15:10:46 x11sslf amdfand[1273420]: 2023-04-21T13:10:46.114338Z DEBUG amdfand::service: Changing speed to 13.00
apr 21 15:10:52 x11sslf amdfand[1273420]: 2023-04-21T13:10:52.114538Z DEBUG amdfand::service: Speed should not change
apr 21 15:10:58 x11sslf amdfand[1273420]: 2023-04-21T13:10:58.114694Z DEBUG amdfand::service: Changing speed to 30.37
apr 21 15:11:04 x11sslf amdfand[1273420]: 2023-04-21T13:11:04.115006Z DEBUG amdfand::service: Changing speed to 19.00
apr 21 15:11:10 x11sslf amdfand[1273420]: 2023-04-21T13:11:10.115259Z DEBUG amdfand::service: Speed should not change
apr 21 15:11:16 x11sslf amdfand[1273420]: 2023-04-21T13:11:16.115387Z DEBUG amdfand::service: Changing speed to 100.00
apr 21 15:11:22 x11sslf amdfand[1273420]: 2023-04-21T13:11:22.115591Z DEBUG amdfand::service: Changing speed to 25.00
apr 21 15:11:28 x11sslf amdfand[1273420]: 2023-04-21T13:11:28.115816Z DEBUG amdfand::service: Changing speed to 100.00
apr 21 15:11:34 x11sslf amdfand[1273420]: 2023-04-21T13:11:34.116374Z DEBUG amdfand::service: Changing speed to 25.00
apr 21 15:11:40 x11sslf amdfand[1273420]: 2023-04-21T13:11:40.116692Z DEBUG amdfand::service: Changing speed to 13.00
apr 21 15:11:46 x11sslf amdfand[1273420]: 2023-04-21T13:11:46.117041Z DEBUG amdfand::service: Speed should not change
apr 21 15:11:52 x11sslf amdfand[1273420]: 2023-04-21T13:11:52.117413Z DEBUG amdfand::service: Speed should not change
apr 21 15:11:58 x11sslf amdfand[1273420]: 2023-04-21T13:11:58.117583Z DEBUG amdfand::service: Changing speed to 16.00
apr 21 15:12:04 x11sslf amdfand[1273420]: 2023-04-21T13:12:04.117809Z DEBUG amdfand::service: Changing speed to 13.00
```

Mapping:

`/etc/amdfand/mapping.toml`

```
temp_input = "temp1_input"
log_level = "Debug"
update_rate = 6000

[[temp_matrix]]
temp = 0.0
speed = 0.0

[[temp_matrix]]
temp = 30.0
speed = 0.0

[[temp_matrix]]
temp = 35.0
speed = 10.0

[[temp_matrix]]
temp = 40.0
speed = 25.0

[[temp_matrix]]
temp = 50.0
speed = 35.0

[[temp_matrix]]
temp = 60.0
speed = 70.0

[[usage_matrix]]
usage = 0.0
speed = 0.0

[[usage_matrix]]
usage = 30.0
speed = 10.0

[[usage_matrix]]
usage = 100.0
speed = 33.0
```

2023-04-21 18:16 UTC, emansom commented
The speed still sporadically goes to 100, while the defined max is set to 33.

With light desktop usage around the 5-10% GPU load, it seems to think the max is reached somehow.

![Schermafdruk van 2023-04-21 20-12-42](https://user-images.githubusercontent.com/981494/233706479-5af6b30c-8e3b-43c6-8afd-a2347712977f.png)

2023-04-21 18:53 UTC, Eraden commented
I added some additional logs. Can you share your logs with me?

2023-04-21 20:22 UTC, emansom commented
Appreciate the detailed instructions, however, you don't have to bother. Have created an AUR package called [amdfand](https://aur.archlinux.org/packages/amdfand) and am building from a locally modified version that pulls the `feature-gpu-usage` branch. 🙂 

Debug log:
```
apr 21 22:13:39 x11sslf systemd[1]: Started AMD GPU fan daemon.
apr 21 22:13:39 x11sslf amdfand[1412949]: 2023-04-21T20:13:39.324597Z DEBUG amdgpu::lock_file: Creating pid lock for path "/var/lib/amdfand/amdfand.pid"
apr 21 22:13:39 x11sslf amdfand[1412949]: 2023-04-21T20:13:39.324613Z DEBUG amdgpu::lock_file: PID LOCK acquiring /var/lib/amdfand/amdfand.pid
apr 21 22:13:39 x11sslf amdfand[1412949]: 2023-04-21T20:13:39.324620Z DEBUG amdgpu::lock_file: No collision detected
apr 21 22:13:39 x11sslf amdfand[1412949]: 2023-04-21T20:13:39.324686Z  INFO amdgpu::utils: opening hw mon for Card(0)
apr 21 22:13:39 x11sslf amdfand[1412949]: 2023-04-21T20:13:39.324718Z  INFO amdgpu::utils: is vendor ok? true
apr 21 22:13:39 x11sslf amdfand[1412949]: 2023-04-21T20:13:39.324739Z  INFO amdgpu::utils: is hwmon name ok? true
apr 21 22:13:39 x11sslf amdfand[1412949]: 2023-04-21T20:13:39.324813Z DEBUG amdfand::service: { gpu_temp: 34.00, gpu_usage: 1.00, temp_fan_speed: 8.00, usage_fan_speed: 0.33, value: 8.00 }
apr 21 22:13:39 x11sslf amdfand[1412949]: 2023-04-21T20:13:39.324818Z DEBUG amdfand::service: Changing speed to 8.00
apr 21 22:13:45 x11sslf amdfand[1412949]: 2023-04-21T20:13:45.325084Z DEBUG amdfand::service: { gpu_temp: 33.00, gpu_usage: 1.00, temp_fan_speed: 6.00, usage_fan_speed: 0.33, value: 6.00 }
apr 21 22:13:45 x11sslf amdfand[1412949]: 2023-04-21T20:13:45.325097Z DEBUG amdfand::service: Changing speed to 6.00
apr 21 22:13:51 x11sslf amdfand[1412949]: 2023-04-21T20:13:51.325350Z DEBUG amdfand::service: { gpu_temp: 33.00, gpu_usage: 1.00, temp_fan_speed: 6.00, usage_fan_speed: 0.33, value: 6.00 }
apr 21 22:13:51 x11sslf amdfand[1412949]: 2023-04-21T20:13:51.325365Z DEBUG amdfand::service: Speed should not change
apr 21 22:13:57 x11sslf amdfand[1412949]: 2023-04-21T20:13:57.325730Z DEBUG amdfand::service: { gpu_temp: 33.00, gpu_usage: 0.00, temp_fan_speed: 6.00, usage_fan_speed: 0.00, value: 6.00 }
apr 21 22:13:57 x11sslf amdfand[1412949]: 2023-04-21T20:13:57.325746Z DEBUG amdfand::service: Speed should not change
apr 21 22:14:03 x11sslf amdfand[1412949]: 2023-04-21T20:14:03.325863Z DEBUG amdfand::service: { gpu_temp: 33.00, gpu_usage: 0.00, temp_fan_speed: 6.00, usage_fan_speed: 0.00, value: 6.00 }
apr 21 22:14:03 x11sslf amdfand[1412949]: 2023-04-21T20:14:03.325891Z DEBUG amdfand::service: Speed should not change
apr 21 22:14:09 x11sslf amdfand[1412949]: 2023-04-21T20:14:09.326248Z DEBUG amdfand::service: { gpu_temp: 33.00, gpu_usage: 0.00, temp_fan_speed: 6.00, usage_fan_speed: 0.00, value: 6.00 }
apr 21 22:14:09 x11sslf amdfand[1412949]: 2023-04-21T20:14:09.326264Z DEBUG amdfand::service: Speed should not change
apr 21 22:14:15 x11sslf amdfand[1412949]: 2023-04-21T20:14:15.326622Z DEBUG amdfand::service: { gpu_temp: 33.00, gpu_usage: 0.00, temp_fan_speed: 6.00, usage_fan_speed: 0.00, value: 6.00 }
apr 21 22:14:15 x11sslf amdfand[1412949]: 2023-04-21T20:14:15.326638Z DEBUG amdfand::service: Speed should not change
apr 21 22:14:21 x11sslf amdfand[1412949]: 2023-04-21T20:14:21.326919Z DEBUG amdfand::service: { gpu_temp: 33.00, gpu_usage: 0.00, temp_fan_speed: 6.00, usage_fan_speed: 0.00, value: 6.00 }
apr 21 22:14:21 x11sslf amdfand[1412949]: 2023-04-21T20:14:21.326935Z DEBUG amdfand::service: Speed should not change
apr 21 22:14:27 x11sslf amdfand[1412949]: 2023-04-21T20:14:27.327081Z DEBUG amdfand::service: { gpu_temp: 33.00, gpu_usage: 0.00, temp_fan_speed: 6.00, usage_fan_speed: 0.00, value: 6.00 }
apr 21 22:14:27 x11sslf amdfand[1412949]: 2023-04-21T20:14:27.327098Z DEBUG amdfand::service: Speed should not change
apr 21 22:14:33 x11sslf amdfand[1412949]: 2023-04-21T20:14:33.327240Z DEBUG amdfand::service: { gpu_temp: 34.00, gpu_usage: 0.00, temp_fan_speed: 8.00, usage_fan_speed: 0.00, value: 8.00 }
apr 21 22:14:33 x11sslf amdfand[1412949]: 2023-04-21T20:14:33.327253Z DEBUG amdfand::service: Changing speed to 8.00
apr 21 22:14:39 x11sslf amdfand[1412949]: 2023-04-21T20:14:39.327449Z DEBUG amdfand::service: { gpu_temp: 36.00, gpu_usage: 16.00, temp_fan_speed: 13.00, usage_fan_speed: 5.33, value: 13.00 }
apr 21 22:14:39 x11sslf amdfand[1412949]: 2023-04-21T20:14:39.327464Z DEBUG amdfand::service: Changing speed to 13.00
apr 21 22:14:45 x11sslf amdfand[1412949]: 2023-04-21T20:14:45.327638Z DEBUG amdfand::service: { gpu_temp: 36.00, gpu_usage: 12.00, temp_fan_speed: 13.00, usage_fan_speed: 4.00, value: 13.00 }
apr 21 22:14:45 x11sslf amdfand[1412949]: 2023-04-21T20:14:45.327652Z DEBUG amdfand::service: Speed should not change
apr 21 22:14:51 x11sslf amdfand[1412949]: 2023-04-21T20:14:51.327770Z DEBUG amdfand::service: { gpu_temp: 36.00, gpu_usage: 0.00, temp_fan_speed: 13.00, usage_fan_speed: 0.00, value: 13.00 }
apr 21 22:14:51 x11sslf amdfand[1412949]: 2023-04-21T20:14:51.327782Z DEBUG amdfand::service: Speed should not change
apr 21 22:14:57 x11sslf amdfand[1412949]: 2023-04-21T20:14:57.327942Z DEBUG amdfand::service: { gpu_temp: 36.00, gpu_usage: 0.00, temp_fan_speed: 13.00, usage_fan_speed: 0.00, value: 13.00 }
apr 21 22:14:57 x11sslf amdfand[1412949]: 2023-04-21T20:14:57.327954Z DEBUG amdfand::service: Speed should not change
apr 21 22:15:03 x11sslf amdfand[1412949]: 2023-04-21T20:15:03.328080Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 100.00, temp_fan_speed: 16.00, usage_fan_speed: 100.00, value: 100.00 }
apr 21 22:15:03 x11sslf amdfand[1412949]: 2023-04-21T20:15:03.328095Z DEBUG amdfand::service: Changing speed to 100.00
apr 21 22:15:09 x11sslf amdfand[1412949]: 2023-04-21T20:15:09.328261Z DEBUG amdfand::service: { gpu_temp: 42.00, gpu_usage: 45.00, temp_fan_speed: 27.00, usage_fan_speed: 14.93, value: 27.00 }
apr 21 22:15:09 x11sslf amdfand[1412949]: 2023-04-21T20:15:09.328274Z DEBUG amdfand::service: Changing speed to 27.00
apr 21 22:15:15 x11sslf amdfand[1412949]: 2023-04-21T20:15:15.328455Z DEBUG amdfand::service: { gpu_temp: 36.00, gpu_usage: 0.00, temp_fan_speed: 13.00, usage_fan_speed: 0.00, value: 13.00 }
apr 21 22:15:15 x11sslf amdfand[1412949]: 2023-04-21T20:15:15.328469Z DEBUG amdfand::service: Changing speed to 13.00
apr 21 22:15:21 x11sslf amdfand[1412949]: 2023-04-21T20:15:21.328761Z DEBUG amdfand::service: { gpu_temp: 35.00, gpu_usage: 0.00, temp_fan_speed: 10.00, usage_fan_speed: 0.00, value: 10.00 }
apr 21 22:15:21 x11sslf amdfand[1412949]: 2023-04-21T20:15:21.328777Z DEBUG amdfand::service: Changing speed to 10.00
```

Mapping:

`/etc/amdfand/mapping.toml`
```
temp_input = "temp1_input"
log_level = "Debug"
update_rate = 6000

[[temp_matrix]]
temp = 0.0
speed = 0.0

[[temp_matrix]]
temp = 30.0
speed = 0.0

[[temp_matrix]]
temp = 35.0
speed = 10.0

[[temp_matrix]]
temp = 40.0
speed = 25.0

[[temp_matrix]]
temp = 50.0
speed = 35.0

[[temp_matrix]]
temp = 60.0
speed = 70.0

[[usage_matrix]]
usage = 0.0
speed = 0.0

[[usage_matrix]]
usage = 30.0
speed = 10.0

[[usage_matrix]]
usage = 100.0
speed = 33.0
```

2023-04-21 20:31 UTC, emansom commented
With 2 additional points in the usage matrix:

Debug log:
```
apr 21 22:27:13 x11sslf systemd[1]: Started AMD GPU fan daemon.
apr 21 22:27:13 x11sslf amdfand[1429977]: 2023-04-21T20:27:13.080993Z DEBUG amdgpu::lock_file: Creating pid lock for path "/var/lib/amdfand/amdfand.pid"
apr 21 22:27:13 x11sslf amdfand[1429977]: 2023-04-21T20:27:13.081007Z DEBUG amdgpu::lock_file: PID LOCK acquiring /var/lib/amdfand/amdfand.pid
apr 21 22:27:13 x11sslf amdfand[1429977]: 2023-04-21T20:27:13.081028Z DEBUG amdgpu::lock_file: No collision detected
apr 21 22:27:13 x11sslf amdfand[1429977]: 2023-04-21T20:27:13.081131Z  INFO amdgpu::utils: opening hw mon for Card(0)
apr 21 22:27:13 x11sslf amdfand[1429977]: 2023-04-21T20:27:13.081190Z  INFO amdgpu::utils: is vendor ok? true
apr 21 22:27:13 x11sslf amdfand[1429977]: 2023-04-21T20:27:13.081211Z  INFO amdgpu::utils: is hwmon name ok? true
apr 21 22:27:13 x11sslf amdfand[1429977]: 2023-04-21T20:27:13.081296Z DEBUG amdfand::service: { gpu_temp: 35.00, gpu_usage: 0.00, temp_fan_speed: 10.00, usage_fan_speed: 0.00, value: 10.00 }
apr 21 22:27:13 x11sslf amdfand[1429977]: 2023-04-21T20:27:13.081301Z DEBUG amdfand::service: Changing speed to 10.00
apr 21 22:27:19 x11sslf amdfand[1429977]: 2023-04-21T20:27:19.081604Z DEBUG amdfand::service: { gpu_temp: 35.00, gpu_usage: 0.00, temp_fan_speed: 10.00, usage_fan_speed: 0.00, value: 10.00 }
apr 21 22:27:19 x11sslf amdfand[1429977]: 2023-04-21T20:27:19.081619Z DEBUG amdfand::service: Speed should not change
apr 21 22:27:25 x11sslf amdfand[1429977]: 2023-04-21T20:27:25.081761Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 42.00, temp_fan_speed: 16.00, usage_fan_speed: 13.43, value: 16.00 }
apr 21 22:27:25 x11sslf amdfand[1429977]: 2023-04-21T20:27:25.081774Z DEBUG amdfand::service: Changing speed to 16.00
apr 21 22:27:31 x11sslf amdfand[1429977]: 2023-04-21T20:27:31.081983Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 81.00, temp_fan_speed: 16.00, usage_fan_speed: 25.94, value: 25.94 }
apr 21 22:27:31 x11sslf amdfand[1429977]: 2023-04-21T20:27:31.082011Z DEBUG amdfand::service: Changing speed to 25.94
apr 21 22:27:37 x11sslf amdfand[1429977]: 2023-04-21T20:27:37.082190Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 62.00, temp_fan_speed: 16.00, usage_fan_speed: 19.14, value: 19.14 }
apr 21 22:27:37 x11sslf amdfand[1429977]: 2023-04-21T20:27:37.082235Z DEBUG amdfand::service: Changing speed to 19.14
apr 21 22:27:43 x11sslf amdfand[1429977]: 2023-04-21T20:27:43.082407Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 0.00, temp_fan_speed: 16.00, usage_fan_speed: 0.00, value: 16.00 }
apr 21 22:27:43 x11sslf amdfand[1429977]: 2023-04-21T20:27:43.082419Z DEBUG amdfand::service: Changing speed to 16.00
apr 21 22:27:49 x11sslf amdfand[1429977]: 2023-04-21T20:27:49.082781Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 0.00, temp_fan_speed: 16.00, usage_fan_speed: 0.00, value: 16.00 }
apr 21 22:27:49 x11sslf amdfand[1429977]: 2023-04-21T20:27:49.082793Z DEBUG amdfand::service: Speed should not change
apr 21 22:27:55 x11sslf amdfand[1429977]: 2023-04-21T20:27:55.083023Z DEBUG amdfand::service: { gpu_temp: 39.00, gpu_usage: 100.00, temp_fan_speed: 22.00, usage_fan_speed: 100.00, value: 100.00 }
apr 21 22:27:55 x11sslf amdfand[1429977]: 2023-04-21T20:27:55.083036Z DEBUG amdfand::service: Changing speed to 100.00
apr 21 22:28:01 x11sslf amdfand[1429977]: 2023-04-21T20:28:01.083224Z DEBUG amdfand::service: { gpu_temp: 42.00, gpu_usage: 5.00, temp_fan_speed: 27.00, usage_fan_speed: 1.67, value: 27.00 }
apr 21 22:28:01 x11sslf amdfand[1429977]: 2023-04-21T20:28:01.083240Z DEBUG amdfand::service: Changing speed to 27.00
apr 21 22:28:07 x11sslf amdfand[1429977]: 2023-04-21T20:28:07.083537Z DEBUG amdfand::service: { gpu_temp: 35.00, gpu_usage: 0.00, temp_fan_speed: 10.00, usage_fan_speed: 0.00, value: 10.00 }
apr 21 22:28:07 x11sslf amdfand[1429977]: 2023-04-21T20:28:07.083551Z DEBUG amdfand::service: Changing speed to 10.00
apr 21 22:28:13 x11sslf amdfand[1429977]: 2023-04-21T20:28:13.083988Z DEBUG amdfand::service: { gpu_temp: 35.00, gpu_usage: 0.00, temp_fan_speed: 10.00, usage_fan_speed: 0.00, value: 10.00 }
apr 21 22:28:13 x11sslf amdfand[1429977]: 2023-04-21T20:28:13.084004Z DEBUG amdfand::service: Speed should not change
```

Mapping:

`/etc/amdfand/mapping.toml`

```
temp_input = "temp1_input"
log_level = "Debug"
update_rate = 6000

[[temp_matrix]]
temp = 0.0
speed = 0.0

[[temp_matrix]]
temp = 30.0
speed = 0.0

[[temp_matrix]]
temp = 35.0
speed = 10.0

[[temp_matrix]]
temp = 40.0
speed = 25.0

[[temp_matrix]]
temp = 50.0
speed = 35.0

[[temp_matrix]]
temp = 60.0
speed = 70.0

[[usage_matrix]]
usage = 0.0
speed = 0.0

[[usage_matrix]]
usage = 15.0
speed = 5.0

[[usage_matrix]]
usage = 30.0
speed = 10.0

[[usage_matrix]]
usage = 65.0
speed = 20.0

[[usage_matrix]]
usage = 100.0
speed = 33.0
```

2023-04-22 07:49 UTC, emansom commented
Without any usage matrix defined (commented out), the speed sporadically goes up higher, too. This time to a max of 94 instead of 100.

```
apr 22 09:45:15 x11sslf systemd[1]: Started AMD GPU fan daemon.
apr 22 09:45:15 x11sslf amdfand[1516980]: 2023-04-22T07:45:15.651255Z DEBUG amdgpu::lock_file: Creating pid lock for path "/var/lib/amdfand/amdfand.pid"
apr 22 09:45:15 x11sslf amdfand[1516980]: 2023-04-22T07:45:15.651272Z DEBUG amdgpu::lock_file: PID LOCK acquiring /var/lib/amdfand/amdfand.pid
apr 22 09:45:15 x11sslf amdfand[1516980]: 2023-04-22T07:45:15.651279Z DEBUG amdgpu::lock_file: No collision detected
apr 22 09:45:15 x11sslf amdfand[1516980]: 2023-04-22T07:45:15.651347Z  INFO amdgpu::utils: opening hw mon for Card(0)
apr 22 09:45:15 x11sslf amdfand[1516980]: 2023-04-22T07:45:15.651380Z  INFO amdgpu::utils: is vendor ok? true
apr 22 09:45:15 x11sslf amdfand[1516980]: 2023-04-22T07:45:15.651399Z  INFO amdgpu::utils: is hwmon name ok? true
apr 22 09:45:15 x11sslf amdfand[1516980]: 2023-04-22T07:45:15.651480Z DEBUG amdfand::service: { gpu_temp: 38.00, gpu_usage: 0.00, temp_fan_speed: 19.00, usage_fan_speed: 0.00, value: 19.00 }
apr 22 09:45:15 x11sslf amdfand[1516980]: 2023-04-22T07:45:15.651485Z DEBUG amdfand::service: Changing speed to 19.00
apr 22 09:45:21 x11sslf amdfand[1516980]: 2023-04-22T07:45:21.651797Z DEBUG amdfand::service: { gpu_temp: 38.00, gpu_usage: 0.00, temp_fan_speed: 19.00, usage_fan_speed: 0.00, value: 19.00 }
apr 22 09:45:21 x11sslf amdfand[1516980]: 2023-04-22T07:45:21.651812Z DEBUG amdfand::service: Speed should not change
apr 22 09:45:27 x11sslf amdfand[1516980]: 2023-04-22T07:45:27.652124Z DEBUG amdfand::service: { gpu_temp: 38.00, gpu_usage: 0.00, temp_fan_speed: 19.00, usage_fan_speed: 0.00, value: 19.00 }
apr 22 09:45:27 x11sslf amdfand[1516980]: 2023-04-22T07:45:27.652139Z DEBUG amdfand::service: Speed should not change
apr 22 09:45:33 x11sslf amdfand[1516980]: 2023-04-22T07:45:33.652281Z DEBUG amdfand::service: { gpu_temp: 38.00, gpu_usage: 0.00, temp_fan_speed: 19.00, usage_fan_speed: 0.00, value: 19.00 }
apr 22 09:45:33 x11sslf amdfand[1516980]: 2023-04-22T07:45:33.652295Z DEBUG amdfand::service: Speed should not change
apr 22 09:45:39 x11sslf amdfand[1516980]: 2023-04-22T07:45:39.652421Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 0.00, temp_fan_speed: 16.00, usage_fan_speed: 0.00, value: 16.00 }
apr 22 09:45:39 x11sslf amdfand[1516980]: 2023-04-22T07:45:39.652451Z DEBUG amdfand::service: Changing speed to 16.00
apr 22 09:45:45 x11sslf amdfand[1516980]: 2023-04-22T07:45:45.652703Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 0.00, temp_fan_speed: 16.00, usage_fan_speed: 0.00, value: 16.00 }
apr 22 09:45:45 x11sslf amdfand[1516980]: 2023-04-22T07:45:45.652718Z DEBUG amdfand::service: Speed should not change
apr 22 09:45:51 x11sslf amdfand[1516980]: 2023-04-22T07:45:51.652852Z DEBUG amdfand::service: { gpu_temp: 39.00, gpu_usage: 0.00, temp_fan_speed: 22.00, usage_fan_speed: 0.00, value: 22.00 }
apr 22 09:45:51 x11sslf amdfand[1516980]: 2023-04-22T07:45:51.652867Z DEBUG amdfand::service: Changing speed to 22.00
apr 22 09:45:57 x11sslf amdfand[1516980]: 2023-04-22T07:45:57.653047Z DEBUG amdfand::service: { gpu_temp: 38.00, gpu_usage: 0.00, temp_fan_speed: 19.00, usage_fan_speed: 0.00, value: 19.00 }
apr 22 09:45:57 x11sslf amdfand[1516980]: 2023-04-22T07:45:57.653061Z DEBUG amdfand::service: Changing speed to 19.00
apr 22 09:46:03 x11sslf amdfand[1516980]: 2023-04-22T07:46:03.653342Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 1.00, temp_fan_speed: 16.00, usage_fan_speed: 1.00, value: 16.00 }
apr 22 09:46:03 x11sslf amdfand[1516980]: 2023-04-22T07:46:03.653355Z DEBUG amdfand::service: Changing speed to 16.00
apr 22 09:46:09 x11sslf amdfand[1516980]: 2023-04-22T07:46:09.653518Z DEBUG amdfand::service: { gpu_temp: 38.00, gpu_usage: 0.00, temp_fan_speed: 19.00, usage_fan_speed: 0.00, value: 19.00 }
apr 22 09:46:09 x11sslf amdfand[1516980]: 2023-04-22T07:46:09.653531Z DEBUG amdfand::service: Changing speed to 19.00
apr 22 09:46:15 x11sslf amdfand[1516980]: 2023-04-22T07:46:15.653777Z DEBUG amdfand::service: { gpu_temp: 39.00, gpu_usage: 0.00, temp_fan_speed: 22.00, usage_fan_speed: 0.00, value: 22.00 }
apr 22 09:46:15 x11sslf amdfand[1516980]: 2023-04-22T07:46:15.653789Z DEBUG amdfand::service: Changing speed to 22.00
apr 22 09:46:21 x11sslf amdfand[1516980]: 2023-04-22T07:46:21.654075Z DEBUG amdfand::service: { gpu_temp: 39.00, gpu_usage: 0.00, temp_fan_speed: 22.00, usage_fan_speed: 0.00, value: 22.00 }
apr 22 09:46:21 x11sslf amdfand[1516980]: 2023-04-22T07:46:21.654087Z DEBUG amdfand::service: Speed should not change
apr 22 09:46:27 x11sslf amdfand[1516980]: 2023-04-22T07:46:27.654211Z DEBUG amdfand::service: { gpu_temp: 39.00, gpu_usage: 1.00, temp_fan_speed: 22.00, usage_fan_speed: 1.00, value: 22.00 }
apr 22 09:46:27 x11sslf amdfand[1516980]: 2023-04-22T07:46:27.654223Z DEBUG amdfand::service: Speed should not change
apr 22 09:46:33 x11sslf amdfand[1516980]: 2023-04-22T07:46:33.654386Z DEBUG amdfand::service: { gpu_temp: 38.00, gpu_usage: 0.00, temp_fan_speed: 19.00, usage_fan_speed: 0.00, value: 19.00 }
apr 22 09:46:33 x11sslf amdfand[1516980]: 2023-04-22T07:46:33.654402Z DEBUG amdfand::service: Changing speed to 19.00
apr 22 09:46:39 x11sslf amdfand[1516980]: 2023-04-22T07:46:39.654670Z DEBUG amdfand::service: { gpu_temp: 39.00, gpu_usage: 0.00, temp_fan_speed: 22.00, usage_fan_speed: 0.00, value: 22.00 }
apr 22 09:46:39 x11sslf amdfand[1516980]: 2023-04-22T07:46:39.654683Z DEBUG amdfand::service: Changing speed to 22.00
apr 22 09:46:45 x11sslf amdfand[1516980]: 2023-04-22T07:46:45.654858Z DEBUG amdfand::service: { gpu_temp: 39.00, gpu_usage: 94.00, temp_fan_speed: 22.00, usage_fan_speed: 94.00, value: 94.00 }
apr 22 09:46:45 x11sslf amdfand[1516980]: 2023-04-22T07:46:45.654873Z DEBUG amdfand::service: Changing speed to 94.00
apr 22 09:46:51 x11sslf amdfand[1516980]: 2023-04-22T07:46:51.655019Z DEBUG amdfand::service: { gpu_temp: 38.00, gpu_usage: 0.00, temp_fan_speed: 19.00, usage_fan_speed: 0.00, value: 19.00 }
apr 22 09:46:51 x11sslf amdfand[1516980]: 2023-04-22T07:46:51.655035Z DEBUG amdfand::service: Changing speed to 19.00
apr 22 09:46:57 x11sslf amdfand[1516980]: 2023-04-22T07:46:57.655257Z DEBUG amdfand::service: { gpu_temp: 38.00, gpu_usage: 8.00, temp_fan_speed: 19.00, usage_fan_speed: 8.00, value: 19.00 }
apr 22 09:46:57 x11sslf amdfand[1516980]: 2023-04-22T07:46:57.655271Z DEBUG amdfand::service: Speed should not change
apr 22 09:47:03 x11sslf amdfand[1516980]: 2023-04-22T07:47:03.655514Z DEBUG amdfand::service: { gpu_temp: 38.00, gpu_usage: 0.00, temp_fan_speed: 19.00, usage_fan_speed: 0.00, value: 19.00 }
apr 22 09:47:03 x11sslf amdfand[1516980]: 2023-04-22T07:47:03.655526Z DEBUG amdfand::service: Speed should not change
apr 22 09:47:09 x11sslf amdfand[1516980]: 2023-04-22T07:47:09.655650Z DEBUG amdfand::service: { gpu_temp: 38.00, gpu_usage: 0.00, temp_fan_speed: 19.00, usage_fan_speed: 0.00, value: 19.00 }
apr 22 09:47:09 x11sslf amdfand[1516980]: 2023-04-22T07:47:09.655663Z DEBUG amdfand::service: Speed should not change
apr 22 09:47:15 x11sslf amdfand[1516980]: 2023-04-22T07:47:15.655911Z DEBUG amdfand::service: { gpu_temp: 38.00, gpu_usage: 0.00, temp_fan_speed: 19.00, usage_fan_speed: 0.00, value: 19.00 }
apr 22 09:47:15 x11sslf amdfand[1516980]: 2023-04-22T07:47:15.655932Z DEBUG amdfand::service: Speed should not change
apr 22 09:47:21 x11sslf amdfand[1516980]: 2023-04-22T07:47:21.656138Z DEBUG amdfand::service: { gpu_temp: 38.00, gpu_usage: 0.00, temp_fan_speed: 19.00, usage_fan_speed: 0.00, value: 19.00 }
apr 22 09:47:21 x11sslf amdfand[1516980]: 2023-04-22T07:47:21.656153Z DEBUG amdfand::service: Speed should not change
apr 22 09:47:27 x11sslf amdfand[1516980]: 2023-04-22T07:47:27.656321Z DEBUG amdfand::service: { gpu_temp: 38.00, gpu_usage: 0.00, temp_fan_speed: 19.00, usage_fan_speed: 0.00, value: 19.00 }
apr 22 09:47:27 x11sslf amdfand[1516980]: 2023-04- [...]

2023-04-22 09:31 UTC, emansom commented
Longer debug log. Tested with both matrixes enabled again with an additional point added to the usage matrix to equalise numbers between the matrixes to six. Same thing happens.

<details>
  <summary>Debug log:</summary>

  ```
  apr 22 11:19:38 x11sslf systemd[1]: Started AMD GPU fan daemon.
  apr 22 11:19:38 x11sslf amdfand[1527191]: 2023-04-22T09:19:38.673146Z DEBUG amdgpu::lock_file: Creating pid lock for path "/var/lib/amdfand/amdfand.pid"
  apr 22 11:19:38 x11sslf amdfand[1527191]: 2023-04-22T09:19:38.673165Z DEBUG amdgpu::lock_file: PID LOCK acquiring /var/lib/amdfand/amdfand.pid
  apr 22 11:19:38 x11sslf amdfand[1527191]: 2023-04-22T09:19:38.673172Z DEBUG amdgpu::lock_file: No collision detected
  apr 22 11:19:38 x11sslf amdfand[1527191]: 2023-04-22T09:19:38.673245Z  INFO amdgpu::utils: opening hw mon for Card(0)
  apr 22 11:19:38 x11sslf amdfand[1527191]: 2023-04-22T09:19:38.673279Z  INFO amdgpu::utils: is vendor ok? true
  apr 22 11:19:38 x11sslf amdfand[1527191]: 2023-04-22T09:19:38.673298Z  INFO amdgpu::utils: is hwmon name ok? true
  apr 22 11:19:38 x11sslf amdfand[1527191]: 2023-04-22T09:19:38.673376Z DEBUG amdfand::service: { gpu_temp: 39.00, gpu_usage: 0.00, temp_fan_speed: 22.00, usage_fan_speed: 0.00, value: 22.00 }
  apr 22 11:19:38 x11sslf amdfand[1527191]: 2023-04-22T09:19:38.673382Z DEBUG amdfand::service: Changing speed to 22.00
  apr 22 11:19:44 x11sslf amdfand[1527191]: 2023-04-22T09:19:44.673673Z DEBUG amdfand::service: { gpu_temp: 39.00, gpu_usage: 0.00, temp_fan_speed: 22.00, usage_fan_speed: 0.00, value: 22.00 }
  apr 22 11:19:44 x11sslf amdfand[1527191]: 2023-04-22T09:19:44.673686Z DEBUG amdfand::service: Speed should not change
  apr 22 11:19:50 x11sslf amdfand[1527191]: 2023-04-22T09:19:50.673825Z DEBUG amdfand::service: { gpu_temp: 39.00, gpu_usage: 0.00, temp_fan_speed: 22.00, usage_fan_speed: 0.00, value: 22.00 }
  apr 22 11:19:50 x11sslf amdfand[1527191]: 2023-04-22T09:19:50.673840Z DEBUG amdfand::service: Speed should not change
  apr 22 11:19:56 x11sslf amdfand[1527191]: 2023-04-22T09:19:56.674070Z DEBUG amdfand::service: { gpu_temp: 39.00, gpu_usage: 0.00, temp_fan_speed: 22.00, usage_fan_speed: 0.00, value: 22.00 }
  apr 22 11:19:56 x11sslf amdfand[1527191]: 2023-04-22T09:19:56.674082Z DEBUG amdfand::service: Speed should not change
  apr 22 11:20:02 x11sslf amdfand[1527191]: 2023-04-22T09:20:02.674202Z DEBUG amdfand::service: { gpu_temp: 39.00, gpu_usage: 0.00, temp_fan_speed: 22.00, usage_fan_speed: 0.00, value: 22.00 }
  apr 22 11:20:02 x11sslf amdfand[1527191]: 2023-04-22T09:20:02.674216Z DEBUG amdfand::service: Speed should not change
  apr 22 11:20:08 x11sslf amdfand[1527191]: 2023-04-22T09:20:08.674455Z DEBUG amdfand::service: { gpu_temp: 39.00, gpu_usage: 0.00, temp_fan_speed: 22.00, usage_fan_speed: 0.00, value: 22.00 }
  apr 22 11:20:08 x11sslf amdfand[1527191]: 2023-04-22T09:20:08.674467Z DEBUG amdfand::service: Speed should not change
  apr 22 11:20:14 x11sslf amdfand[1527191]: 2023-04-22T09:20:14.674617Z DEBUG amdfand::service: { gpu_temp: 39.00, gpu_usage: 0.00, temp_fan_speed: 22.00, usage_fan_speed: 0.00, value: 22.00 }
  apr 22 11:20:14 x11sslf amdfand[1527191]: 2023-04-22T09:20:14.674631Z DEBUG amdfand::service: Speed should not change
  apr 22 11:20:20 x11sslf amdfand[1527191]: 2023-04-22T09:20:20.674767Z DEBUG amdfand::service: { gpu_temp: 39.00, gpu_usage: 89.00, temp_fan_speed: 22.00, usage_fan_speed: 29.17, value: 29.17 }
  apr 22 11:20:20 x11sslf amdfand[1527191]: 2023-04-22T09:20:20.674780Z DEBUG amdfand::service: Changing speed to 29.17
  apr 22 11:20:26 x11sslf amdfand[1527191]: 2023-04-22T09:20:26.675051Z DEBUG amdfand::service: { gpu_temp: 39.00, gpu_usage: 45.00, temp_fan_speed: 22.00, usage_fan_speed: 14.29, value: 22.00 }
  apr 22 11:20:26 x11sslf amdfand[1527191]: 2023-04-22T09:20:26.675064Z DEBUG amdfand::service: Changing speed to 22.00
  apr 22 11:20:32 x11sslf amdfand[1527191]: 2023-04-22T09:20:32.675303Z DEBUG amdfand::service: { gpu_temp: 39.00, gpu_usage: 0.00, temp_fan_speed: 22.00, usage_fan_speed: 0.00, value: 22.00 }
  apr 22 11:20:32 x11sslf amdfand[1527191]: 2023-04-22T09:20:32.675315Z DEBUG amdfand::service: Speed should not change
  apr 22 11:20:38 x11sslf amdfand[1527191]: 2023-04-22T09:20:38.675446Z DEBUG amdfand::service: { gpu_temp: 40.00, gpu_usage: 0.00, temp_fan_speed: 25.00, usage_fan_speed: 0.00, value: 25.00 }
  apr 22 11:20:38 x11sslf amdfand[1527191]: 2023-04-22T09:20:38.675459Z DEBUG amdfand::service: Changing speed to 25.00
  apr 22 11:20:44 x11sslf amdfand[1527191]: 2023-04-22T09:20:44.675689Z DEBUG amdfand::service: { gpu_temp: 40.00, gpu_usage: 100.00, temp_fan_speed: 25.00, usage_fan_speed: 100.00, value: 100.00 }
  apr 22 11:20:44 x11sslf amdfand[1527191]: 2023-04-22T09:20:44.675700Z DEBUG amdfand::service: Changing speed to 100.00
  apr 22 11:20:50 x11sslf amdfand[1527191]: 2023-04-22T09:20:50.675863Z DEBUG amdfand::service: { gpu_temp: 40.00, gpu_usage: 87.00, temp_fan_speed: 25.00, usage_fan_speed: 28.48, value: 28.48 }
  apr 22 11:20:50 x11sslf amdfand[1527191]: 2023-04-22T09:20:50.675875Z DEBUG amdfand::service: Changing speed to 28.48
  apr 22 11:20:56 x11sslf amdfand[1527191]: 2023-04-22T09:20:56.676079Z DEBUG amdfand::service: { gpu_temp: 44.00, gpu_usage: 100.00, temp_fan_speed: 29.00, usage_fan_speed: 100.00, value: 100.00 }
  apr 22 11:20:56 x11sslf amdfand[1527191]: 2023-04-22T09:20:56.676091Z DEBUG amdfand::service: Changing speed to 100.00
  apr 22 11:21:02 x11sslf amdfand[1527191]: 2023-04-22T09:21:02.676254Z DEBUG amdfand::service: { gpu_temp: 45.00, gpu_usage: 100.00, temp_fan_speed: 30.00, usage_fan_speed: 100.00, value: 100.00 }
  apr 22 11:21:02 x11sslf amdfand[1527191]: 2023-04-22T09:21:02.676266Z DEBUG amdfand::service: Speed should not change
  apr 22 11:21:08 x11sslf amdfand[1527191]: 2023-04-22T09:21:08.676392Z DEBUG amdfand::service: { gpu_temp: 45.00, gpu_usage: 86.00, temp_fan_speed: 30.00, usage_fan_speed: 28.13, value: 30.00 }
  apr 22 11:21:08 x11sslf amdfand[1527191]: 2023-04-22T09:21:08.676406Z DEBUG amdfand::service: Changing speed to 30.00
  apr 22 11:21:14 x11sslf amdfand[1527191]: 2023-04-22T09:21:14.676570Z DEBUG amdfand::service: { gpu_temp: 45.00, gpu_usage: 100.00, temp_fan_speed: 30.00, usage_fan_speed: 100.00, value: 100.00 }
  apr 22 11:21:14 x11sslf amdfand[1527191]: 2023-04-22T09:21:14.676582Z DEBUG amdfand::service: Changing speed to 100.00
  apr 22 11:21:20 x11sslf amdfand[1527191]: 2023-04-22T09:21:20.676737Z DEBUG amdfand::service: { gpu_temp: 45.00, gpu_usage: 100.00, temp_fan_speed: 30.00, usage_fan_speed: 100.00, value: 100.00 }
  apr 22 11:21:20 x11sslf amdfand[1527191]: 2023-04-22T09:21:20.676750Z DEBUG amdfand::service: Speed should not change
  apr 22 11:21:26 x11sslf amdfand[1527191]: 2023-04-22T09:21:26.676876Z DEBUG amdfand::service: { gpu_temp: 45.00, gpu_usage: 100.00, temp_fan_speed: 30.00, usage_fan_speed: 100.00, value: 100.00 }
  apr 22 11:21:26 x11sslf amdfand[1527191]: 2023-04-22T09:21:26.676904Z DEBUG amdfand::service: Speed should not change
  apr 22 11:21:32 x11sslf amdfand[1527191]: 2023-04-22T09:21:32.677098Z DEBUG amdfand::service: { gpu_temp: 45.00, gpu_usage: 0.00, temp_fan_speed: 30.00, usage_fan_speed: 0.00, value: 30.00 }
  apr 22 11:21:32 x11sslf amdfand[1527191]: 2023-04-22T09:21:32.677112Z DEBUG amdfand::service: Changing speed to 30.00
  apr 22 11:21:38 x11sslf amdfand[1527191]: 2023-04-22T09:21:38.677276Z DEBUG amdfand::service: { gpu_temp: 46.00, gpu_usage: 100.00, temp_fan_speed: 31.00, usage_fan_speed: 100.00, value: 100.00 }
  apr 22 11:21:38 x11sslf amdfand[1527191]: 2023-04-22T09:21:38.677287Z DEBUG amdfand::service: Changing speed to 100.00
  apr 22 11:21:44 x11sslf amdfand[1527191]: 2023-04-22T09:21:44.677657Z DEBUG amdfand::service: { gpu_temp: 45.00, gpu_usage: 100.00, temp_fan_speed: 30.00, usage_fan_speed: 100.00, value: 100.00 }
  apr 22 11:21:44 x11sslf amdfand[1527191]: 2023-04-22T09:21:44.677670Z DEBUG amdfand::service: Speed should not change
  [...]

2023-04-28 15:37 UTC, Eraden commented
I'm currently stuck with my day-to-day job. I'll try to improve this implementation ASAP but I can't promise anything now

2023-04-29 14:01 UTC, emansom requested changes
With these changes locally, it works beautifully as intended:

2023-04-29 14:03 UTC, emansom commented
As `git diff`:

```diff
diff --git a/crates/amdgpu-config/src/fan.rs b/crates/amdgpu-config/src/fan.rs
index 41573c9..ed7c22d 100644
--- a/crates/amdgpu-config/src/fan.rs
+++ b/crates/amdgpu-config/src/fan.rs
@@ -108,11 +108,11 @@ impl Config {
     pub fn fan_speed_for_temp(&self, temp: f64) -> f64 {
         let idx = match self.temp_matrix.iter().rposition(|p| p.temp <= temp) {
             Some(idx) => idx,
-            _ => return self.min_speed(),
+            _ => return self.min_speed_for_temp(),
         };
 
         if idx == self.temp_matrix.len() - 1 {
-            return self.max_speed();
+            return self.max_speed_for_temp();
         }
 
         linear_map(
@@ -125,12 +125,13 @@ impl Config {
     }
 
     pub fn fan_speed_for_usage(&self, usage: f64) -> f64 {
-        let Some(idx) = self.usage_matrix.iter().rposition(|p| p.usage <= usage) else {
-            return 0.0;
+        let idx = match self.usage_matrix.iter().rposition(|p| p.usage <= usage) {
+            Some(idx) => idx,
+            _ => return self.min_speed_for_usage(),
         };
 
         if idx == self.usage_matrix.len() - 1 {
-            return 100.0;
+            return self.max_speed_for_usage();
         }
 
         linear_map(
@@ -158,14 +159,22 @@ impl Config {
         self.update_rate
     }
 
-    fn min_speed(&self) -> f64 {
+    fn min_speed_for_temp(&self) -> f64 {
         self.temp_matrix.first().map(|p| p.speed).unwrap_or(0f64)
     }
 
-    fn max_speed(&self) -> f64 {
+    fn max_speed_for_temp(&self) -> f64 {
         self.temp_matrix.last().map(|p| p.speed).unwrap_or(100f64)
     }
 
+    fn min_speed_for_usage(&self) -> f64 {
+        self.usage_matrix.first().map(|p| p.speed).unwrap_or(0f64)
+    }
+
+    fn max_speed_for_usage(&self) -> f64 {
+        self.usage_matrix.last().map(|p| p.speed).unwrap_or(100f64)
+    }
+
     fn default_refresh_delay() -> u64 {
         4000
     }
```

2023-04-29 14:09 UTC, emansom commented
Debug log and mapping with the local changes suggested above. It now works as expected, ramping up as defined within the mapping:

<details>
  <summary>Debug log:</summary>
  
  Debug log with the local changes above:

  ```shell
  ➜  ~ journalctl -f -u amdfand.service
  apr 29 15:38:04 x11sslf amdfand[43962]: 2023-04-29T13:38:04.228569Z DEBUG amdgpu::lock_file: No collision detected
  apr 29 15:38:04 x11sslf amdfand[43962]: 2023-04-29T13:38:04.244436Z  INFO amdgpu::utils: opening hw mon for Card(0)
  apr 29 15:38:04 x11sslf amdfand[43962]: 2023-04-29T13:38:04.244483Z  INFO amdgpu::utils: is vendor ok? true
  apr 29 15:38:04 x11sslf amdfand[43962]: 2023-04-29T13:38:04.244503Z  INFO amdgpu::utils: is hwmon name ok? true
  apr 29 15:38:04 x11sslf amdfand[43962]: 2023-04-29T13:38:04.244584Z DEBUG amdfand::service: { gpu_temp: 35.00, gpu_usage: 0.00, temp_fan_speed: 10.00, usage_fan_speed: 0.00, value: 10.00 }
  apr 29 15:38:04 x11sslf amdfand[43962]: 2023-04-29T13:38:04.244592Z DEBUG amdfand::service: Changing speed to 10.00
  apr 29 15:38:10 x11sslf amdfand[43962]: 2023-04-29T13:38:10.245012Z DEBUG amdfand::service: { gpu_temp: 35.00, gpu_usage: 0.00, temp_fan_speed: 10.00, usage_fan_speed: 0.00, value: 10.00 }
  apr 29 15:38:10 x11sslf amdfand[43962]: 2023-04-29T13:38:10.245028Z DEBUG amdfand::service: Speed should not change
  apr 29 15:38:16 x11sslf amdfand[43962]: 2023-04-29T13:38:16.245459Z DEBUG amdfand::service: { gpu_temp: 36.00, gpu_usage: 0.00, temp_fan_speed: 13.00, usage_fan_speed: 0.00, value: 13.00 }
  apr 29 15:38:16 x11sslf amdfand[43962]: 2023-04-29T13:38:16.245475Z DEBUG amdfand::service: Changing speed to 13.00
  apr 29 15:38:22 x11sslf amdfand[43962]: 2023-04-29T13:38:22.245934Z DEBUG amdfand::service: { gpu_temp: 35.00, gpu_usage: 0.00, temp_fan_speed: 10.00, usage_fan_speed: 0.00, value: 10.00 }
  apr 29 15:38:22 x11sslf amdfand[43962]: 2023-04-29T13:38:22.245949Z DEBUG amdfand::service: Changing speed to 10.00
  apr 29 15:38:28 x11sslf amdfand[43962]: 2023-04-29T13:38:28.246263Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 0.00, temp_fan_speed: 16.00, usage_fan_speed: 0.00, value: 16.00 }
  apr 29 15:38:28 x11sslf amdfand[43962]: 2023-04-29T13:38:28.246278Z DEBUG amdfand::service: Changing speed to 16.00
  apr 29 15:38:34 x11sslf amdfand[43962]: 2023-04-29T13:38:34.246452Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 1.00, temp_fan_speed: 16.00, usage_fan_speed: 0.33, value: 16.00 }
  apr 29 15:38:34 x11sslf amdfand[43962]: 2023-04-29T13:38:34.246496Z DEBUG amdfand::service: Speed should not change
  apr 29 15:38:40 x11sslf amdfand[43962]: 2023-04-29T13:38:40.246632Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 10.00, temp_fan_speed: 16.00, usage_fan_speed: 3.33, value: 16.00 }
  apr 29 15:38:40 x11sslf amdfand[43962]: 2023-04-29T13:38:40.246644Z DEBUG amdfand::service: Speed should not change
  apr 29 15:38:46 x11sslf amdfand[43962]: 2023-04-29T13:38:46.246786Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 83.00, temp_fan_speed: 16.00, usage_fan_speed: 27.09, value: 27.09 }
  apr 29 15:38:46 x11sslf amdfand[43962]: 2023-04-29T13:38:46.246814Z DEBUG amdfand::service: Changing speed to 27.09
  apr 29 15:38:52 x11sslf amdfand[43962]: 2023-04-29T13:38:52.246990Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 38.00, temp_fan_speed: 16.00, usage_fan_speed: 12.29, value: 16.00 }
  apr 29 15:38:52 x11sslf amdfand[43962]: 2023-04-29T13:38:52.247002Z DEBUG amdfand::service: Changing speed to 16.00
  apr 29 15:38:58 x11sslf amdfand[43962]: 2023-04-29T13:38:58.247245Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 0.00, temp_fan_speed: 16.00, usage_fan_speed: 0.00, value: 16.00 }
  apr 29 15:38:58 x11sslf amdfand[43962]: 2023-04-29T13:38:58.247258Z DEBUG amdfand::service: Speed should not change
  apr 29 15:39:04 x11sslf amdfand[43962]: 2023-04-29T13:39:04.247379Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 6.00, temp_fan_speed: 16.00, usage_fan_speed: 2.00, value: 16.00 }
  apr 29 15:39:04 x11sslf amdfand[43962]: 2023-04-29T13:39:04.247391Z DEBUG amdfand::service: Speed should not change
  apr 29 15:39:10 x11sslf amdfand[43962]: 2023-04-29T13:39:10.247627Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 0.00, temp_fan_speed: 16.00, usage_fan_speed: 0.00, value: 16.00 }
  apr 29 15:39:10 x11sslf amdfand[43962]: 2023-04-29T13:39:10.247640Z DEBUG amdfand::service: Speed should not change
  apr 29 15:39:16 x11sslf amdfand[43962]: 2023-04-29T13:39:16.247764Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 90.00, temp_fan_speed: 16.00, usage_fan_speed: 29.52, value: 29.52 }
  apr 29 15:39:16 x11sslf amdfand[43962]: 2023-04-29T13:39:16.247778Z DEBUG amdfand::service: Changing speed to 29.52
  apr 29 15:39:22 x11sslf amdfand[43962]: 2023-04-29T13:39:22.247965Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 8.00, temp_fan_speed: 16.00, usage_fan_speed: 2.67, value: 16.00 }
  apr 29 15:39:22 x11sslf amdfand[43962]: 2023-04-29T13:39:22.247977Z DEBUG amdfand::service: Changing speed to 16.00
  apr 29 15:39:28 x11sslf amdfand[43962]: 2023-04-29T13:39:28.248226Z DEBUG amdfand::service: { gpu_temp: 37.00, gpu_usage: 2.00, temp_fan_speed: 16.00, usage_fan_speed: 0.67, value: 16.00 }
  apr 29 15:39:28 x11sslf amdfand[43962]: 2023-04-29T13:39:28.248239Z DEBUG amdfand::service: Speed should not change
  apr 29 15:39:34 x11sslf amdfand[43962]: 2023-04-29T13:39:34.248420Z DEBUG amdfand::service: { gpu_temp: 42.00, gpu_usage: 100.00, temp_fan_speed: 27.00, usage_fan_speed: 33.00, value: 33.00 }
  apr 29 15:39:34 x11sslf amdfand[43962]: 2023-04-29T13:39:34.248432Z DEBUG amdfand::service: Changing speed to 33.00
  apr 29 15:39:40 x11sslf amdfand[43962]: 2023-04-29T13:39:40.248607Z DEBUG amdfand::service: { gpu_temp: 43.00, gpu_usage: 82.00, temp_fan_speed: 28.00, usage_fan_speed: 26.74, value: 28.00 }
  apr 29 15:39:40 x11sslf amdfand[43962]: 2023-04-29T13:39:40.248624Z DEBUG amdfand::service: Changing speed to 28.00
  apr 29 15:39:46 x11sslf amdfand[43962]: 2023-04-29T13:39:46.248833Z DEBUG amdfand::service: { gpu_temp: 44.00, gpu_usage: 100.00, temp_fan_speed: 29.00, usage_fan_speed: 33.00, value: 33.00 }
  apr 29 15:39:46 x11sslf amdfand[43962]: 2023-04-29T13:39:46.248848Z DEBUG amdfand::service: Changing speed to 33.00
  apr 29 15:39:52 x11sslf amdfand[43962]: 2023-04-29T13:39:52.249026Z DEBUG amdfand::service: { gpu_temp: 44.00, gpu_usage: 100.00, temp_fan_speed: 29.00, usage_fan_speed: 33.00, value: 33.00 }
  apr 29 15:39:52 x11sslf amdfand[43962]: 2023-04-29T13:39:52.249038Z DEBUG amdfand::service: Speed should not change
  apr 29 15:39:58 x11sslf amdfand[43962]: 2023-04-29T13:39:58.249157Z DEBUG amdfand::service: { gpu_temp: 44.00, gpu_usage: 100.00, temp_fan_speed: 29.00, usage_fan_speed: 33.00, value: 33.00 }
  apr 29 15:39:58 x11sslf amdfand[43962]: 2023-04-29T13:39:58.249170Z DEBUG amdfand::service: Speed should not change
  apr 29 15:40:04 x11sslf amdfand[43962]: 2023-04-29T13:40:04.249293Z DEBUG amdfand::service: { gpu_temp: 44.00, gpu_usage: 88.00, temp_fan_speed: 29.00, usage_fan_speed: 28.83, value: 29.00 }
  apr 29 15:40:04 x11sslf amdfand[43962]: 2023-04-29T13:40:04.249305Z DEBUG amdfand::service: Changing speed to 29.00
  apr 29 15:40:10 x11sslf amdfand[43962]: 2023-04-29T13:40:10.249502Z DEBUG amdfand::service: { gpu_temp: 45.00, gpu_usage: 100.00, temp_fan_speed: 30.00, usage_fan_speed: 33.00, value: 33.00 }
  apr 29 15:40:10 x11sslf amdfand[43962]: 2023-04-29T13:40:10.249514Z DEBUG amdfand::service: Changing speed to 33.00
  apr 29 15:40:16 x11sslf amdfand[43962]: 2023-04-29T13:40:16.249867Z DEBUG amdfand::service: { gpu_temp: 45.00, gpu_usage: 27.00, temp_fan_speed: 30.00, usage_fan_speed: 9.00, value: 30.00 }
  apr 29 15:40:16 x11sslf amdfand[43962]: 2023-04-29T13:40:16.249879Z DEBUG amdfand::service: Changing speed to 30.00
  apr 29 15:40:22 x11sslf amdfand[43962]: 2023-04-29T13:40:22.250031Z DEBUG amdfand::service: { gpu_temp: 45.00, gpu_usage: 100.00, temp_ [...]

2023-04-29 17:34 UTC, emansom commented
During gaming, the fans do still ramp up and down between low and high curve a little too much. To normalize the RPM speed adjustments more, `amdfand` could implement another polling technique for only the GPU usage calculation. 

Where it would poll more frequently (e.g. 100ms) independently of the defined `update_rate` and then pick the highest max encountered usage of that independent GPU usage poll when the regular tick cycle runs.

2023-11-18 10:11 UTC, merged